#File compression using numpy operations

In [1]:
import numpy as np
petrol = np.genfromtxt("petrol.txt",skip_header=1)
#here default whitespace delimiter is used
petrol

array([[9.0000e+00, 3.5710e+03, 1.9760e+03, 5.2500e-01, 5.4100e+02],
       [9.0000e+00, 4.0920e+03, 1.2500e+03, 5.7200e-01, 5.2400e+02],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01, 5.6100e+02],
       [7.5000e+00, 4.8700e+03, 2.3510e+03, 5.2900e-01, 4.1400e+02],
       [8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01, 4.1000e+02],
       [1.0000e+01, 5.3420e+03, 1.3330e+03, 5.7100e-01, 4.5700e+02],
       [8.0000e+00, 5.3190e+03, 1.1868e+04, 4.5100e-01, 3.4400e+02],
       [8.0000e+00, 5.1260e+03, 2.1380e+03, 5.5300e-01, 4.6700e+02],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01, 4.6400e+02],
       [7.0000e+00, 4.5120e+03, 8.5070e+03, 5.5200e-01, 4.9800e+02],
       [8.0000e+00, 4.3910e+03, 5.9390e+03, 5.3000e-01, 5.8000e+02],
       [7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01, 4.7100e+02],
       [7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01, 5.2500e+02],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01, 5.0800e+02],
       [7.0000e+00, 4.3320e+03, 8.

In [2]:
petrol.shape

(48, 5)

In [3]:
np.isnan(petrol)#To know the Nan points, we get true in the places that are nan

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, Fal

In [4]:
#converting nan to num,replace nan with -1 as it contains one nan value
#nan_to_num is a function already present in numpy
petrol_new= np.nan_to_num(petrol, nan=-1)
petrol_new

array([[ 9.0000e+00,  3.5710e+03,  1.9760e+03,  5.2500e-01,  5.4100e+02],
       [ 9.0000e+00,  4.0920e+03,  1.2500e+03,  5.7200e-01,  5.2400e+02],
       [ 9.0000e+00,  3.8650e+03,  1.5860e+03,  5.8000e-01,  5.6100e+02],
       [ 7.5000e+00,  4.8700e+03,  2.3510e+03,  5.2900e-01,  4.1400e+02],
       [ 8.0000e+00,  4.3990e+03,  4.3100e+02,  5.4400e-01,  4.1000e+02],
       [ 1.0000e+01,  5.3420e+03,  1.3330e+03,  5.7100e-01,  4.5700e+02],
       [ 8.0000e+00,  5.3190e+03,  1.1868e+04,  4.5100e-01,  3.4400e+02],
       [ 8.0000e+00,  5.1260e+03,  2.1380e+03,  5.5300e-01,  4.6700e+02],
       [ 8.0000e+00,  4.4470e+03,  8.5770e+03,  5.2900e-01,  4.6400e+02],
       [ 7.0000e+00,  4.5120e+03,  8.5070e+03,  5.5200e-01,  4.9800e+02],
       [ 8.0000e+00,  4.3910e+03,  5.9390e+03,  5.3000e-01,  5.8000e+02],
       [ 7.5000e+00,  5.1260e+03,  1.4186e+04,  5.2500e-01,  4.7100e+02],
       [ 7.0000e+00,  4.8170e+03,  6.9300e+03,  5.7400e-01,  5.2500e+02],
       [ 7.0000e+00,  4.2070e+03,  6.5

In [5]:
np.isnan(petrol_new) #To verify 

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, Fal

In [6]:
#To save this txt in a new file 
np.savetxt('petrol_new.txt',petrol_new,delimiter=',')
petrol_new

array([[ 9.0000e+00,  3.5710e+03,  1.9760e+03,  5.2500e-01,  5.4100e+02],
       [ 9.0000e+00,  4.0920e+03,  1.2500e+03,  5.7200e-01,  5.2400e+02],
       [ 9.0000e+00,  3.8650e+03,  1.5860e+03,  5.8000e-01,  5.6100e+02],
       [ 7.5000e+00,  4.8700e+03,  2.3510e+03,  5.2900e-01,  4.1400e+02],
       [ 8.0000e+00,  4.3990e+03,  4.3100e+02,  5.4400e-01,  4.1000e+02],
       [ 1.0000e+01,  5.3420e+03,  1.3330e+03,  5.7100e-01,  4.5700e+02],
       [ 8.0000e+00,  5.3190e+03,  1.1868e+04,  4.5100e-01,  3.4400e+02],
       [ 8.0000e+00,  5.1260e+03,  2.1380e+03,  5.5300e-01,  4.6700e+02],
       [ 8.0000e+00,  4.4470e+03,  8.5770e+03,  5.2900e-01,  4.6400e+02],
       [ 7.0000e+00,  4.5120e+03,  8.5070e+03,  5.5200e-01,  4.9800e+02],
       [ 8.0000e+00,  4.3910e+03,  5.9390e+03,  5.3000e-01,  5.8000e+02],
       [ 7.5000e+00,  5.1260e+03,  1.4186e+04,  5.2500e-01,  4.7100e+02],
       [ 7.0000e+00,  4.8170e+03,  6.9300e+03,  5.7400e-01,  5.2500e+02],
       [ 7.0000e+00,  4.2070e+03,  6.5

In [7]:
!ls -lh #to view all the file sizes

total 16K
-rw-r--r-- 1 root root 5.9K Jul 28 13:10 petrol_new.txt
-rw-r--r-- 1 root root 1.2K Jul 28 13:05 petrol.txt
drwxr-xr-x 1 root root 4.0K Jul 10 16:29 sample_data


In [8]:
#when the file size is very large, change it to compressed format as follows
np.savez_compressed("petrol_z", petrol_new) #compressed format

In [14]:
!ls -lh petrol_z.npz

-rw-r--r-- 1 root root 1012 Jul 28 13:11 petrol_z.npz
